### ISSUE TITLE
doc: error in readme

### ISSUE THREAD

**Issue by Guekka** [nix-community/dconf2nix#75]
In the readme example, `current=uint32 0` is converted to `current = "uint32 0";`

However, it should be `current = lib.hm.gvariant.mkUint32 0`

I assume the program behaviour is correct and it is a typo in the readme only, since this function exists

**Comment by jtojnar** [comment]
Thanks. This has been fixed in https://github.com/nix-community/dconf2nix/commit/c8aa732bc03f0136a40c413d1a7d993c01a4bfd6
