### ISSUE TITLE
Stepping away, looking for maintainers

### ISSUE THREAD

**Issue by gvolpe** [nix-community/dconf2nix#84]
It's been a fun ride writing this toy project to satisfy two of my needs:

1. Generate a `dconf.nix` expected by Home Manager.
2. Play around with parser combinators in Haskell.

However, time has passed and I no longer have a need for this utility. Neither I have the time nor the willing to keep on working on it, but after seeing more issues and PRs being raised recently, I thought at least I'd post an update on the status of this project.

**I will not contribute to this project anymore, but I would be happy to assign new maintainers.** 

Just leave a comment below if you're up for the task.

**Comment by rycee** [comment]
Thanks for creating and maintaining this tool! I'm sure it has been a great help for many users.

**Comment by jtojnar** [comment]
Thanks for everything.

I would be willing to take over the maintenance (mostly low key though).

**Comment by gvolpe** [comment]
Hi @jtojnar , happy to donate this over to `nix-community` if you're willing to get the paperwork done :)

**Comment by jtojnar** [comment]
You should be able to move it to `nix-community` on https://github.com/gvolpe/dconf2nix/transfer.

**Comment by gvolpe** [comment]
I get this error message: `You don’t have the permission to create public repositories on nix-community`

**Comment by zowoq** [comment]
Need to be a member of nix-community to transfer the repo, @gvolpe I've send you an invite.

**Comment by gvolpe** [comment]
@zowoq thanks, done! ✅ Happy to help with anything else, at your disposal @jtojnar  🙏🏽

**Comment by adisbladis** [comment]
I have updated the repo description indicating @jtojnar as the maintainer & created a dconf2nix team where both @jtojnar and @gvolpe are maintainers.

**Comment by zvictor** [comment]
Seems like this has been resolved. Is there a reason to keep it pinned?

**Comment by gvolpe** [comment]
@zvictor thanks for the reminder, unpinned :)

**Comment by zvictor** [comment]
Unfortunately no release has been published since you left, even though there were a few bug fixes pushed.

would it be possible to publish a new release any time soon? 😊

**Comment by jtojnar** [comment]
Sorry, we still need to update home manager and Nixpkgs to support the new
features. Might be a topic for NixCon hackday.
