### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by sjhaleprogrammer** [nix-community/dconf2nix#87]
### Type of bug

Parsing error

### Version

0.1.1

### Did you test against master?

- [ ] Certainly

### Error message (if not timeout)

```shell
dconf2nix: "dconf.settings" (line 263, column 34):
unexpected "{"
expecting "<("
CallStack (from HasCallStack):
  error, called at src/DConf2Nix.hs:35:16 in dconf2nix-0.1.1-Kj3okwrvVsmLXSmJ1JaeH6:DConf2Nix
```

### DConf input

```ini
[org/gnome/shell]
app-picker-layout=[{'Utilities': <{'position': <0>}>}]
```

**Comment by montchr** [comment]
I've managed to work around this by deleting that setting from the file using the [crudini](https://github.com/pixelb/crudini) tool for performing CRUD operations on INI files. I am not sure whether the output format of `dconf dump` is valid INI, but `crudini` can handle it just fine.

Example:

```sh
dconf dump / > dconf.settings
crudini --del dconf.settings 'org/gnome/shell' 'app-picker-layout'
dconf2nix -i dconf.settings -o dconf.settings.nix
```

**Comment by drmikecrowe** [comment]
I used sed:

```sh
mike-nixos  main @ 44750a0 ⩮∽+⇡ ❄️ flakeShell-env! dconf dump / | sed '/</d' > dconf.ini
```
